In [1]:
import torch

1 Create a tensor a from list(range(9)). Predict and then check the size, offset,
and stride. 

a Create a new tensor using b = a.view(3, 3). What does view do? Check
that a and b share the same storage. \
b Create a tensor c = b[1:,1:]. Predict and then check the size, offset, and
stride.

2 Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?

a Apply the function element-wise to a. Why does it return an error? \
b What operation is required to make the function work?\
c Is there a version of your function that operates in place?

In [3]:
#1.

list_ = list(range(9))
tensor_ = torch.tensor(list_)

In [5]:
tensor_.size(), tensor_.storage_offset(), tensor_.stride()

(torch.Size([9]), 0, (1,))

In [7]:
#1.a 

b = tensor_.view(3,3)

In [8]:
b.size(), b.storage_offset(), b.stride()

(torch.Size([3, 3]), 0, (3, 1))

In [14]:
b.storage() is tensor_.storage()

False

In [12]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [13]:
tensor_.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [15]:
c = b[1:,1:]

In [16]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [18]:
print(torch.cos(b))

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837],
        [ 0.9602,  0.7539, -0.1455]])


In [22]:
for i in tensor_:
    print(torch.cos(tensor_))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
